### PR TITLE
Adding success() support + updating README.md

### PR DESCRIPTION
**Pull request by clementblanco**
It's pretty self explanatory.

### CODE REVIEW

**Comment by FokkeZB** [comment]
Thanks!

Could you also send a PR for the example app in the [test](https://github.com/FokkeZB/nl.fokkezb.loading/tree/test) branch to demonstrate it?

**Comment by FokkeZB** [comment]
Thanks for updating the sample as well, however..

- When I hit the _SUCCESS example button nothing happens_
- When I then hit the _VIEW example_ button I see:

screen shot 2016-05-23 at 11 54 11

**Comment by Claymm** [comment]
Mmmm I'm never displaying both at the same time as I'm hiding/showing it myself within the codebase.
I'll investigate and hide the previous one if success is called. I think at the moment it's just creating a new one.

**Comment by FokkeZB** [comment]
Closing for inactivity

**Pull request closed without merging**
